# Generated by Django 4.1.3 on 2023-08-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantrecognitionapp', '0002_alter_annotation_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plantrecognitionapp.plantimage'),
        ),
    ]
