# Generated by Django 4.1.3 on 2023-08-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantrecognitionapp', '0003_alter_annotation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='image',
        ),
    ]
