# Generated by Django 4.1.3 on 2023-08-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantrecognitionapp', '0005_remove_annotation_height_remove_annotation_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
