# Generated by Django 4.1.3 on 2023-08-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantrecognitionapp', '0008_remove_annotation_color_remove_annotation_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='plant_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plantrecognitionapp.plantimage'),
        ),
    ]
